import {
  DroneControlAuthority,
  DroneControlMode,
  DroneInsuranceStatus,
  DroneMaintenanceStatus,
  DroneStatus,
  PilotAccountStatus,
  PilotCertificateType,
  PilotControlMode,
  type DroneInfo,
  type PilotInfo,
} from "@/api/resource/types";

export function buildDroneMockData(): DroneInfo[] {
  return [
    {
      id: 1,
      snCode: "0ABCD1EFGH2JK345",
      droneName: "珠海巡警-01",
      brand: "大疆",
      model: "Matrice 350 RTK",
      controlMode: DroneControlMode.PLATFORM,
      airportName: "珠海分局机场-01",
      organization: "公安局",
      controlAuthority: [DroneControlAuthority.EXCLUSIVE],
      status: DroneStatus.ONLINE,
      maintenanceStatus: DroneMaintenanceStatus.NEEDS_MAINTENANCE,
      insuranceStatus: DroneInsuranceStatus.NORMAL,
      createdAt: "2025-11-14 08:43:30",
      remark: "日常巡逻机组",
    },
    {
      id: 2,
      snCode: "3LMN4OPQR5ST678UV",
      droneName: "河道巡检-03",
      brand: "大疆",
      model: "Mavic 3E",
      controlMode: DroneControlMode.REMOTE,
      airportName: "-",
      organization: "公安局",
      controlAuthority: [DroneControlAuthority.EXCLUSIVE, DroneControlAuthority.SHARED],
      status: DroneStatus.OFFLINE,
      maintenanceStatus: DroneMaintenanceStatus.NORMAL,
      insuranceStatus: DroneInsuranceStatus.EXPIRING_SOON,
      createdAt: "2025-11-14 08:43:35",
      remark: "河道日常巡查",
    },
    {
      id: 3,
      snCode: "9WXY0ZABC1DEF234G",
      droneName: "城管执法-02",
      brand: "大疆",
      model: "Mavic 3T",
      controlMode: DroneControlMode.REMOTE,
      airportName: "-",
      organization: "交通局",
      controlAuthority: [DroneControlAuthority.EXCLUSIVE, DroneControlAuthority.SHARED],
      status: DroneStatus.OFFLINE,
      maintenanceStatus: DroneMaintenanceStatus.NORMAL,
      insuranceStatus: DroneInsuranceStatus.NORMAL,
      createdAt: "2025-11-14 09:30:55",
      remark: "城区巡查执法",
    },
    {
      id: 4,
      snCode: "5HIJ6KLM7NOP890RS",
      droneName: "演示测试机",
      brand: "大疆",
      model: "Air 2S",
      controlMode: DroneControlMode.REMOTE,
      airportName: "-",
      organization: "交通局",
      controlAuthority: [DroneControlAuthority.TEAM, DroneControlAuthority.SHARED],
      status: DroneStatus.OFFLINE,
      maintenanceStatus: DroneMaintenanceStatus.OVERDUE,
      insuranceStatus: DroneInsuranceStatus.NORMAL,
      createdAt: "2025-11-14 08:43:40",
      remark: "演示培训使用",
    },
    {
      id: 5,
      snCode: "2TUV3WXY4ZAB567CD",
      droneName: "应急测绘-01",
      brand: "纵横",
      model: "CW-15",
      controlMode: DroneControlMode.PLATFORM,
      airportName: "香洲移动站",
      organization: "交通局",
      controlAuthority: [DroneControlAuthority.TEAM],
      status: DroneStatus.ONLINE,
      maintenanceStatus: DroneMaintenanceStatus.NORMAL,
      insuranceStatus: DroneInsuranceStatus.EXPIRED,
      createdAt: "2025-11-14 09:30:55",
      remark: "应急响应使用",
    },
    {
      id: 6,
      snCode: "8EFG9HIJ0KLM123NP",
      droneName: "珠海交警-01",
      brand: "大疆",
      model: "Matrice 30",
      controlMode: DroneControlMode.PLATFORM,
      airportName: "珠海高栏机场",
      organization: "交通局",
      controlAuthority: [
        DroneControlAuthority.TEAM,
        DroneControlAuthority.SHARED,
        DroneControlAuthority.EXCLUSIVE,
      ],
      status: DroneStatus.MAINTENANCE,
      maintenanceStatus: DroneMaintenanceStatus.NORMAL,
      insuranceStatus: DroneInsuranceStatus.NORMAL,
      createdAt: "2025-11-14 08:43:40",
      remark: "高速巡查任务",
    },
    {
      id: 7,
      snCode: "4QRS5TUV6WXY789ZA",
      droneName: "林业巡查-01",
      brand: "大疆",
      model: "Mavic 3M",
      controlMode: DroneControlMode.PLATFORM,
      airportName: "湿地森林公园站",
      organization: "林业局",
      controlAuthority: [
        DroneControlAuthority.TEAM,
        DroneControlAuthority.SHARED,
        DroneControlAuthority.EXCLUSIVE,
      ],
      status: DroneStatus.ONLINE,
      maintenanceStatus: DroneMaintenanceStatus.NORMAL,
      insuranceStatus: DroneInsuranceStatus.NORMAL,
      createdAt: "2025-11-14 09:30:55",
      remark: "林业资源巡护",
    },
    {
      id: 8,
      snCode: "1BCDE2FGHIJ45K6LM",
      droneName: "环保监测-01",
      brand: "极飞",
      model: "XB2025",
      controlMode: DroneControlMode.PLATFORM,
      airportName: "香洲区环保方舱",
      organization: "生态环境局",
      controlAuthority: [
        DroneControlAuthority.TEAM,
        DroneControlAuthority.SHARED,
        DroneControlAuthority.EXCLUSIVE,
      ],
      status: DroneStatus.ONLINE,
      maintenanceStatus: DroneMaintenanceStatus.NEEDS_MAINTENANCE,
      insuranceStatus: DroneInsuranceStatus.EXPIRING_SOON,
      createdAt: "2025-11-14 08:43:40",
      remark: "环保监测任务",
    },
  ];
}

export function buildPilotMockData(): PilotInfo[] {
  return [
    {
      id: 1,
      username: "wangwei01",
      name: "王伟",
      phone: "138****1234",
      organization: "市公安局-珠海分局",
      department: "警务飞巡中心",
      certificateType: PilotCertificateType.AOPA,
      certificateNo: "AOPA-2025-001",
      controlMode: PilotControlMode.AUTO,
      assignedDroneName: "珠海巡警-01",
      status: PilotAccountStatus.ENABLED,
      email: "wangwei01@example.com",
      createdAt: "2025-11-14 08:43:30",
      issuedDate: "2025-01-12",
      validityYears: 3,
      certificateScanUrl: "https://dummyimage.com/160x160/0b2040/ffffff&text=AOPA",
    },
    {
      id: 2,
      username: "lina_jiaotong",
      name: "李娜",
      phone: "159****5678",
      organization: "市交通运输局-路政支队",
      department: "路政巡检组",
      certificateType: PilotCertificateType.AOPA,
      certificateNo: "AOPA-2025-018",
      controlMode: PilotControlMode.MANUAL,
      assignedDroneName: "珠海交警-01",
      status: PilotAccountStatus.DISABLED,
      email: "lina_jiaotong@example.com",
      createdAt: "2025-11-14 08:43:35",
      issuedDate: "2025-02-21",
      validityYears: 2,
      certificateScanUrl: "https://dummyimage.com/160x160/163760/ffffff&text=AOPA",
    },
    {
      id: 3,
      username: "zhangqiang_epb",
      name: "张强",
      phone: "177****9012",
      organization: "市生态环境局-监察支队",
      department: "环境监测组",
      certificateType: PilotCertificateType.ALPA,
      certificateNo: "ALPA-2025-007",
      controlMode: PilotControlMode.HYBRID,
      assignedDroneName: "环保监测-01",
      status: PilotAccountStatus.DISABLED,
      email: "zhangqiang_epb@example.com",
      createdAt: "2025-11-14 09:30:55",
      issuedDate: "2025-03-15",
      validityYears: 3,
      certificateScanUrl: "https://dummyimage.com/160x160/123052/ffffff&text=ALPA",
    },
    {
      id: 4,
      username: "chenlei_emerg",
      name: "陈磊",
      phone: "188****3456",
      organization: "市应急管理局-救援队",
      department: "应急测绘组",
      certificateType: PilotCertificateType.ALPA,
      certificateNo: "ALPA-2025-019",
      controlMode: PilotControlMode.AUTO,
      assignedDroneName: "应急测绘-01",
      status: PilotAccountStatus.ENABLED,
      email: "chenlei_emerg@example.com",
      createdAt: "2025-11-14 08:43:40",
      issuedDate: "2025-01-08",
      validityYears: 2,
      certificateScanUrl: "https://dummyimage.com/160x160/14476a/ffffff&text=ALPA",
    },
    {
      id: 5,
      username: "liuyuan_cg",
      name: "刘源",
      phone: "147****7890",
      organization: "市城市管理局-执法大队",
      department: "城管执法组",
      certificateType: PilotCertificateType.UTC,
      certificateNo: "UTC-2025-006",
      controlMode: PilotControlMode.AUTO,
      assignedDroneName: "暂未分配",
      status: PilotAccountStatus.ENABLED,
      email: "liuyuan_cg@example.com",
      createdAt: "2025-11-14 09:30:55",
      issuedDate: "2025-04-10",
      validityYears: 1,
      certificateScanUrl: "https://dummyimage.com/160x160/1c5d82/ffffff&text=UTC",
    },
    {
      id: 6,
      username: "sunzhe_forest",
      name: "孙哲",
      phone: "135****1122",
      organization: "市林业局-巡查科",
      department: "林区巡查组",
      certificateType: PilotCertificateType.UTC,
      certificateNo: "UTC-2025-012",
      controlMode: PilotControlMode.HYBRID,
      assignedDroneName: "林业巡查-01",
      status: PilotAccountStatus.ENABLED,
      email: "sunzhe_forest@example.com",
      createdAt: "2025-11-14 08:43:40",
      issuedDate: "2025-05-06",
      validityYears: 2,
      certificateScanUrl: "https://dummyimage.com/160x160/0f2f4a/ffffff&text=UTC",
    },
    {
      id: 7,
      username: "hongtao_water",
      name: "洪涛",
      phone: "153****3344",
      organization: "市水务局-河湖管理处",
      department: "河湖管理组",
      certificateType: PilotCertificateType.UTC,
      certificateNo: "UTC-2025-015",
      controlMode: PilotControlMode.MANUAL,
      assignedDroneName: "暂未分配",
      status: PilotAccountStatus.ENABLED,
      email: "hongtao_water@example.com",
      createdAt: "2025-11-14 09:30:55",
      issuedDate: "2025-05-18",
      validityYears: 1,
      certificateScanUrl: "https://dummyimage.com/160x160/123d60/ffffff&text=UTC",
    },
  ];
}
